spring:
  datasource:
    url: jdbc:mysql://localhost:3306/repl?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wjdghk79M
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show: true
    properties:
      hibernate:
        format_sql: true
