spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/repl?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: wjdghk79M
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  address: 192.168.45.225
  port: 8080